<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.0.0.379
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Registo Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_reCAPTCHA2_private_key' => 'Invalid reCAPTCHA 2.0 private key.',
		'invalid_reCAPTCHA2_server_response' => 'Invalid reCAPTCHA 2.0 server response.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'plastklaer@gmail.com',
		'to' => 'plastklaer@gmail.com'
	),
	'fields' => array(
		'custom_U6225' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Nome de Utilizador',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Nome de Utilizador\' is required.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'Email',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Email\' is required.',
				'format' => 'Field \'Email\' has an invalid email.'
			)
		),
		'custom_U6336' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Repita o seu Email',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Repita o seu Email\' is required.'
			)
		),
		'custom_U6348' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Password',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Password\' is required.'
			)
		),
		'custom_U6360' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Confirme a sua password',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Confirme a sua password\' is required.'
			)
		)
	)
);

process_form($form);
?>
